routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function(){

	/** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
  Auth::routes();
  Route::get('/logout','Auth\LoginController@userLogout')->name('userLogout');
	Route::get('/', 'HomeController@index')->name('home');
  Route::get('/addads', 'AdsController@index')->name('ads');

  Route::resource('/addcar', 'HomeCarscontroller');
  Route::resource('/addbuild', 'HomeBuildController');
  Route::resource('/addelectronic','HomeElectroController');
  Route::resource('/addjobs', 'homeJobsController');
  Route::resource('/addother', 'HomeOtherController');

  Route::get('/scrap', 'HomeOtherController@scrap');
  Route::get('/house', 'HomeOtherController@house');
  Route::get('/others', 'HomeOtherController@other');

  
  //profile
  Route::get('/profile', 'AdsController@profile')->name('profile');
	Route::post('/profile','AdsController@updateprofile')->name('updateprofile');
  Route::get('/myads', 'AdsController@myads')->name('myads');

 //profile company ...
  Route::get('/employer', 'CompanyController@employer')->name('add_employer');
  Route::get('/compProfile', 'CompanyController@compprofile')->name('compprofile');
  Route::get('/editemployer', 'CompanyController@editemployer')->name('editemployer');
  //pages
  Route::get('/offers', 'HomeController@offers')->name('offers');
  Route::get('/contact','HomeController@contact');
  Route::get('/terms','HomeController@terms');
  Route::get('/privacy','HomeController@privacy');
  Route::get('/about','HomeController@about');
  Route::get('/company','HomeController@company');
  Route::get('/companytype/{cat}','HomeController@companytype');
  Route::get('/companyprofile/{slug}','HomeController@companyprofile');
});

//route admin
Route::prefix('control')->group(function() {

  Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('control.auth.login');
  Route::post('/login', 'Auth\AdminLoginController@login')->name('control.auth.login.submit');
  Route::get('/logout', 'Auth\AdminLoginController@logout')->name('control.auth.logout');
  Route::get('/', 'AdminController@index')->name('control.index');

  //register 
  Route::resource('/role', 'AdminRegisterController');
  Route::post('/status','AdminRegisterController@status');

  // Password reset routes
  Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('control.auth.password.email');
  Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('control.auth.password.request');
  Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
  Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('control.auth.password.reset');

  Route::get('/page/privacy', 'AdminPageController@showprivacy')->name('control.page.showprivacy');
  Route::post('/page/privacy', 'AdminPageController@saveprivacy')->name('control.page.saveprivacy');

  Route::get('/page/terms', 'AdminPageController@showterms')->name('control.page.showterms');
  Route::post('/page/terms', 'AdminPageController@saveterms')->name('control.page.saveterms');

  Route::get('/page/about', 'AdminPageController@showabout')->name('control.page.showabout');
  Route::post('/page/about', 'AdminPageController@saveabout')->name('control.page.saveabout');

  Route::get('/city', 'AdminPageController@showcity')->name('control.city.showcity');
  Route::post('/city', 'AdminPageController@savecity')->name('control.city.savecity');

  Route::get('/settings', 'AdminPageController@showsettings')->name('control.settings.showsettings');
  Route::post('/settings', 'AdminPageController@savesettings')->name('control.settings.savesettings');

  //ads
  Route::get('/adsStep/new', 'AdminAdsCarsController@newadsCars');
  Route::get('/adsStep/published', 'AdminAdsCarsController@publishedCars');
  Route::get('/adsStep/feature', 'AdminAdsCarsController@featureCars');
  Route::get('/adsStep/trashed', 'AdminAdsCarsController@trashedCars');

  Route::get('/adsStep/trashed', 'AdminAdsCarsController@trashedCars');
  
  //menu
  Route::resource('/adsStep', 'AdminAdsCarsController');
  Route::post('/adsStep/getAjax','AdminAdsCarsController@getAjax');

  //Route::get('/wmenuindex', 'AdminMenucontroller@wmenuindex');
  //route resource
  Route::resource('/category/cars', 'AdminCarsController');
  Route::resource('/category/builds', 'AdminBuildController');
  Route::resource('/category/electro', 'AdminElectroController');
  Route::resource('/category/jobs', 'AdminJobsController');
  Route::resource('/category/others', 'AdminOthersController');

  Route::resource('/category/lance', 'AdminLanceController');
  Route::resource('/category/scrap', 'AdminScrapController');
  Route::resource('/category/runt', 'AdminRuntController');
  Route::resource('/category/homes', 'AdminHomesController');

  Route::resource('/ads', 'AdminAdscontroller');
  Route::resource('/offer', 'AdminOffersController');
  Route::resource('/client', 'AdminClientController');
  Route::resource('/cat', 'AdminCatController');
  Route::resource('/company', 'AdminCompanyController');
  Route::resource('/tags', 'AdminTagcontroller');
  Route::resource('/employer', 'AdminEmployerController');

});

resources/views/control/settings/create.blade.php
@extends('control.layouts.navbar')
@section('navbar')
<div class="layout-content">
    <div class="layout-content-body">
        <div class="title-bar">
            <h1 class="title-bar-title">
              <span class="d-ib">المعلومات العامة </span>
            </h1>
        </div>
        <div class="row gutter-xs">
             @if ($message = Session::get('success'))
                <div class="alert-success success">
                    <p>{{ $message }}</p> 
                </div>
            @endif
            {!! Form::open(array('url' => 'control/settings', 'class' => 'form','data-toggle' => 'validator','files' => true)) !!}
                
                <div class="col-lg-6">
                    <div class="form-group">
                        {!! Form::label('اسم الموقع بالعربية') !!}
                        {!! Form::text('sitename',$settings->sitename, 
                            array('required', 
                                'class'=>'form-control', 
                                'placeholder'=>'اسم الموقع بالعربية')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::hidden('settingsid',$settings->id, 
                            array('required')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('حساب فيس بوك') !!}
                        {!! Form::text('site_facebook',$settings->site_facebook, 
                            array('required', 
                            'class'=>'form-control','placeholder'=>'حساب فيس بوك')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('حساب توتير') !!}
                        {!! Form::text('site_twitter',$settings->site_twitter, 
                            array('required', 
                            'class'=>'form-control','placeholder'=>'حساب توتير')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('حساب يوبوب') !!}
                        {!! Form::text('site_youtube',$settings->site_youtube, 
                            array('required', 
                            'class'=>'form-control','placeholder'=>'حساب يوتوب')) !!}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        {!! Form::label('اسم الموقع بالانجليزية') !!}
                        {!! Form::text('sitename_en',$settings->sitename_en, 
                            array('required', 
                            'class'=>'form-control','placeholder'=>'اسم الموقع بالانجليزية')) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('حساب انستغرام') !!}
                        {!! Form::text('site_instagram',$settings->site_instagram, 
                            array('required', 
                            'class'=>'form-control','placeholder'=>'حساب انستغرام')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('رقم الهاتف') !!}
                        {!! Form::text('site_phone',$settings->site_phone, 
                            array('required', 
                            'class'=>'form-control','placeholder'=>'رقم الهاتف')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('البريد الالكتروني') !!}
                        {!! Form::text('site_email',$settings->site_email, 
                            array('required', 
                            'class'=>'form-control','placeholder'=>'البريد الالكتروني')) !!}
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        {!! Form::label('شعار الموقع') !!}
                        {!! Form::file('sitelogo',
                            array('class'=>'form-control')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('وصف الموقع بالعربية') !!}
                        {!! Form::textarea('description',$settings->description, 
                            array('required', 
                            'class'=>'form-control')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('وصف الموفع بالانجليزية') !!}
                        {!! Form::textarea('description_en',$settings->description_en, 
                            array('required', 
                            'class'=>'form-control')) !!}
                    </div>
                </div>
                
                <div class="form-group">
                    {!! Form::submit('تحديث المعلومات ', 
                    array('class'=>'btn btn-primary btn-block')) !!}
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/control/settings/edit.blade.php
@extends('control.layouts.navbar')
@section('navbar')
<div class="layout-content">
    <div class="layout-content-body">
        <div class="title-bar">
            <h1 class="title-bar-title">
              <span class="d-ib">تعديل العرض</span>
            </h1>
        </div>
        <div class="row gutter-xs">
            <a href="{{URL::to('control/offer')}}" class="btn btn-success pull-right">كل العروض</a>
            </br>
             @if ($message = Session::get('success'))
                <div class="alert-success success">
                    <p>{{ $message }}</p>
                </div>
            @endif
             {!! Form::model($offers, [
                    'method' => 'PATCH',
                    'route' => ['offer.update', $offers->id],
                    'class' => 'form','data-toggle' => 'validator','files' => true
                    ]) !!}
                <div class="form-group">
                    {!! Form::label('اسم العرض') !!}
                    {!! Form::text('offername', null, 
                        array('required', 
                            'class'=>'form-control', 
                            'placeholder'=>'ضع اسم مميز للعرض')) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('طبيعة الاعلان') !!}
                    {!! Form::select('offertype', [1 => 'عرض عادي', 2 => 'عرض مميز'],$offers->offertype, ['required','class'=>'form-control']); !!}
                </div>
                <div class="form-group">
                    {!! Form::label('رابط الاعلان') !!}
                    {!! Form::text('offerurl', null, 
                        array('required','class'=>'form-control','placeholder'=>'رابط الاعلان')) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('تاريخ الانتهاء') !!}
                    {!! Form::text('offerenddate', null, 
                        array('required','data-provide'=>'datepicker','class'=>'form-control','placeholder'=>'تاربخ نهاية العرض')) !!}
    
               </div>
                <div class="form-group">
                    {!! Form::label('رفع الصورة') !!}
                    {!! Form::file('offerimage', null, 
                        array('required','class'=>'form-control')) !!}
                </div>
                <div class="form-group">
                    {!! Form::submit('تحديث العرض', 
                    array('class'=>'btn btn-primary btn-block')) !!}
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/control/settings/index.blade.php
@extends('control.layouts.navbar')
@section('navbar')
<div class="layout-content">
    <div class="layout-content-body">
        <div class="title-bar">
            <h1 class="title-bar-title">
              <span class="d-ib">كل العروض </span>
            </h1>
        </div>
        <div class="row gutter-xs">
            <a href="{{url('control/offer/create')}}" class="btn btn-success">اضافة عرض جديد</a>
            </br>
            <table id="demo-dynamic-tables-2" class="table table-middle">
                <thead>
                    <tr>
                    <th>
                        <label class="custom-control custom-control-primary custom-checkbox">
                        <input id="checkAll" class="custom-control-input" type="checkbox">
                        <span class="custom-control-indicator"></span>
                        </label>
                    </th>
                    <th>معاينة</th>
                    <th>اسم العرض</th>
                    <th>طبيعة الاعلان</th>
                    <th>رابط الاعلان</th>
                    <th>تاريخ الانتهاء</th>
                    <th>الحالة</th>
                    <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($offers as $offer)
                        <tr>
                            <td>
                                <img class="rounded" width="40" height="40" src="{{url('public/assets/img/')}}/{{$offer->offerimage}}" alt=""/>
                            </td>
                            <td>{{$offer->offername}}</td>
                            <td>
                                @if($offer->offertype==1) 
                                   عرض عادي
                                @elseif($offer->offertype==2)
                                    عرض مميز
                                @endif
                            </td>
                            <td>{{$offer->offerurl}}</td>
                            <td>{{$offer->offerenddate}}</td>
                            <td>
                            @if($offer->status ==0 )
                                <label class="label label-success label-pill">اعلان صالح</label>
                            @else
                                <label class="label label-primary label-pill">منتهي</label>
                            @endif
                            </td>
                            <td>
                                <div class="btn-group pull-right dropdown">
                                <button class="btn btn-link link-muted" aria-haspopup="true" data-toggle="dropdown" type="button">
                                    <span class="icon icon-ellipsis-h icon-lg icon-fw"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="{{route('offer.edit',$offer->id)}}"  class="btn-link goldorders" >تعديل العرض</a></li>
                                    <li><a href="{{route('offer.destroy',$offer->id)}}"  class="btn-link goldorders" >ايقاف العرض</a></li>
                                </ul>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection