routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
],
function(){

	/** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
  Auth::routes();
  Route::get('/logout','Auth\LoginController@userLogout')->name('userLogout');
	Route::get('/', 'HomeController@index')->name('home');
  Route::get('/addads', 'AdsController@index')->name('ads');

  Route::resource('/addcar', 'HomeCarscontroller');
  Route::resource('/addbuild', 'HomeBuildController');
  Route::resource('/addelectronic','HomeElectroController');
  Route::resource('/addjobs', 'homeJobsController');
  Route::resource('/addother', 'HomeOtherController');

  Route::get('/scrap', 'HomeOtherController@scrap');
  Route::get('/house', 'HomeOtherController@house');
  Route::get('/others', 'HomeOtherController@other');

  
  //profile
  Route::get('/profile', 'AdsController@profile')->name('profile');
	Route::post('/profile','AdsController@updateprofile')->name('updateprofile');
  Route::get('/myads', 'AdsController@myads')->name('myads');

 //profile company ...
  Route::get('/employer', 'CompanyController@employer')->name('add_employer');
  Route::get('/compProfile', 'CompanyController@compprofile')->name('compprofile');
  Route::get('/editemployer', 'CompanyController@editemployer')->name('editemployer');
  //pages
  Route::get('/offers', 'HomeController@offers')->name('offers');
  Route::get('/contact','HomeController@contact');
  Route::get('/terms','HomeController@terms');
  Route::get('/privacy','HomeController@privacy');
  Route::get('/about','HomeController@about');
  Route::get('/company','HomeController@company');
  Route::get('/companytype/{cat}','HomeController@companytype');
  Route::get('/companyprofile/{slug}','HomeController@companyprofile');
});

//route admin
Route::prefix('control')->group(function() {

  Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('control.auth.login');
  Route::post('/login', 'Auth\AdminLoginController@login')->name('control.auth.login.submit');
  Route::get('/logout', 'Auth\AdminLoginController@logout')->name('control.auth.logout');
  Route::get('/', 'AdminController@index')->name('control.index');

  //register 
  Route::resource('/role', 'AdminRegisterController');
  Route::post('/status','AdminRegisterController@status');

  // Password reset routes
  Route::post('/password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('control.auth.password.email');
  Route::get('/password/reset', 'Auth\AdminForgotPasswordController@showLinkRequestForm')->name('control.auth.password.request');
  Route::post('/password/reset', 'Auth\AdminResetPasswordController@reset');
  Route::get('/password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('control.auth.password.reset');

  Route::get('/page/privacy', 'AdminPageController@showprivacy')->name('control.page.showprivacy');
  Route::post('/page/privacy', 'AdminPageController@saveprivacy')->name('control.page.saveprivacy');

  Route::get('/page/terms', 'AdminPageController@showterms')->name('control.page.showterms');
  Route::post('/page/terms', 'AdminPageController@saveterms')->name('control.page.saveterms');

  Route::get('/page/about', 'AdminPageController@showabout')->name('control.page.showabout');
  Route::post('/page/about', 'AdminPageController@saveabout')->name('control.page.saveabout');

  Route::get('/city', 'AdminPageController@showcity')->name('control.city.showcity');
  Route::post('/city', 'AdminPageController@savecity')->name('control.city.savecity');

  Route::get('/settings', 'AdminPageController@showsettings')->name('control.settings.showsettings');
  Route::post('/settings', 'AdminPageController@savesettings')->name('control.settings.savesettings');

  //ads
  Route::get('/adsStep/new', 'AdminAdsCarsController@newadsCars');
  Route::get('/adsStep/published', 'AdminAdsCarsController@publishedCars');
  Route::get('/adsStep/feature', 'AdminAdsCarsController@featureCars');
  Route::get('/adsStep/trashed', 'AdminAdsCarsController@trashedCars');

  Route::get('/adsStep/trashed', 'AdminAdsCarsController@trashedCars');
  
  //menu
  Route::resource('/adsStep', 'AdminAdsCarsController');
  Route::post('/adsStep/getAjax','AdminAdsCarsController@getAjax');

  //Route::get('/wmenuindex', 'AdminMenucontroller@wmenuindex');
  //route resource
  Route::resource('/category/cars', 'AdminCarsController');
  Route::resource('/category/builds', 'AdminBuildController');
  Route::resource('/category/electro', 'AdminElectroController');
  Route::resource('/category/jobs', 'AdminJobsController');
  Route::resource('/category/others', 'AdminOthersController');

  Route::resource('/category/lance', 'AdminLanceController');
  Route::resource('/category/scrap', 'AdminScrapController');
  Route::resource('/category/runt', 'AdminRuntController');
  Route::resource('/category/homes', 'AdminHomesController');

  Route::resource('/ads', 'AdminAdscontroller');
  Route::resource('/offer', 'AdminOffersController');
  Route::resource('/client', 'AdminClientController');
  Route::resource('/cat', 'AdminCatController');
  Route::resource('/company', 'AdminCompanyController');
  Route::resource('/tags', 'AdminTagcontroller');
  Route::resource('/employer', 'AdminEmployerController');

});

app/Electro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Electro extends Model
{
    //
    protected $fillable = [
        'catname','catname_en','title','catflag','catcolor','catphoto','cathome'
    ];
}

resources/views/control/category/electro/create.blade.php
@extends('control.layouts.navbar')
@section('navbar')
<div class="layout-content">
    <div class="layout-content-body">
        <div class="title-bar">
            <h1 class="title-bar-title">
              <span class="d-ib">اضافة قسم جديد  </span>
            </h1>
        </div>
        <div class="row gutter-xs">
            <a href="{{url('control/category/electro')}}" class="btn btn-success pull-right">كل الاقسام</a>
            </br>
             @if ($message = Session::get('success'))
                <div class="alert-success success">
                    <p>{{ $message }}</p>
                </div>
            @endif
             {!! Form::open(array('url' => 'control/category/electro', 'class' => 'form','data-toggle' => 'validator','files' => true)) !!}
                <div class="form-group">
                    {!! Form::label('اسم القسم') !!}
                    {!! Form::text('catname', null, 
                        array('required', 
                            'class'=>'form-control', 
                            'placeholder'=>'اكتب اسم القسم')) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('اسم القسم بالانجليزية') !!}
                    {!! Form::text('catname_en', null, 
                        array('required', 
                            'class'=>'form-control', 
                            'placeholder'=>'اسم القسم بالانجليزية')) !!}
                </div>
                <div class="form-group">
                        {!! Form::label('لون الشعار ') !!}
                        {!! Form::text('catcolor', null, 
                            array('required','class'=>'form-control','placeholder'=>'اكثت لون الشعار مثلا green ')) !!}
                </div>
                <div class="form-group catflag">
                    {!! Form::label('شعار القسم http://fontawesome.io/icons/') !!}
                    {!! Form::text('catflag', null, 
                        array('class'=>'form-control','placeholder'=>'ضع شعار القسم مثلا fa fa-car ')) !!}
                </div>
                <div class="form-group catphoto" style="display:none">
                    {!! Form::label('رفع شعار القسم') !!}
                    {!! Form::file('catphoto', null, 
                        array('class'=>'form-control')) !!}
                </div>
                <div class="form-group">
                   <label class="custom-control custom-control-primary custom-checkbox">
                        <input class="custom-control-input isAgeSelected" type="checkbox" name="mode" value="1">
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-label">رفع صورة للقسم</span>
                    </label>
                </div>
                <div class="form-group">
                   <label class="custom-control custom-control-primary custom-checkbox">
                        <input class="custom-control-input" type="checkbox" name="cathome" value="1">
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-label">اظهار القسم في الصفحة الرئسية</span>
                    </label>
                </div>
                <div class="form-group">
                    {!! Form::submit('نشر القسم', 
                    array('class'=>'btn btn-primary btn-block')) !!}
                </div>
            {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/control/category/electro/edit.blade.php
@extends('control.layouts.navbar')
@section('navbar')
<div class="layout-content">
    <div class="layout-content-body">
        <div class="title-bar">
            <h1 class="title-bar-title">
              <span class="d-ib">تعديل العرض</span>
            </h1>
        </div>
        <div class="row gutter-xs">
            <a href="{{URL::to('control/category/electro')}}" class="btn btn-success pull-right">كل العروض</a>
            </br>
             @if ($message = Session::get('success'))
                <div class="alert-success success">
                    <p>{{ $message }}</p>
                </div>
            @endif
             {!! Form::model($cats, [
                    'method' => 'PATCH',
                    'route' => ['electro.update', $cats->id],
                    'class' => 'form','data-toggle' => 'validator','files' => true
                    ]) !!}
                <div class="form-group">
                    {!! Form::label('اسم القسم') !!}
                    {!! Form::text('catname', null, 
                        array('required', 
                            'class'=>'form-control', 
                            'placeholder'=>'اكتب اسم القسم')) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('اسم القسم بالانجليزية') !!}
                    {!! Form::text('catname_en', null, 
                        array('required', 
                            'class'=>'form-control', 
                            'placeholder'=>'اسم القسم بالانجليزية')) !!}
                </div>
                <div class="form-group">
                        {!! Form::label('لون الشعار ') !!}
                        {!! Form::text('catcolor', null, 
                            array('required','class'=>'form-control','placeholder'=>'اكثت لون الشعار مثلا green ')) !!}
                </div>
                <div class="form-group catflag">
                    {!! Form::label('شعار القسم http://fontawesome.io/icons/') !!}
                    {!! Form::text('catflag', null, 
                        array('class'=>'form-control','placeholder'=>'ضع شعار القسم مثلا fa fa-car ')) !!}
                </div>
                <div class="form-group catphoto" style="display:none">
                    {!! Form::label('رفع شعار القسم') !!}
                    {!! Form::file('catphoto', null, 
                        array('class'=>'form-control')) !!}
                </div>
                <div class="form-group">
                   <label class="custom-control custom-control-primary custom-checkbox">
                        <input class="custom-control-input isAgeSelected" type="checkbox" name="mode" value="1">
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-label">رفع صورة للقسم</span>
                    </label>
                </div>
                <div class="form-group">
                   <label class="custom-control custom-control-primary custom-checkbox">
                        <input class="custom-control-input" type="checkbox" name="cathome" value="1">
                        <span class="custom-control-indicator"></span>
                        <span class="custom-control-label">اظهار القسم في الصفحة الرئسية</span>
                    </label>
                </div>
                <div class="form-group">
                    {!! Form::submit('نشر القسم', 
                    array('class'=>'btn btn-primary btn-block')) !!}
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/control/category/electro/index.blade.php
@extends('control.layouts.navbar')
@section('navbar')
<div class="layout-content">
    <div class="layout-content-body">
        <div class="title-bar">
            <h1 class="title-bar-title">
              <span class="d-ib">الكترونيات</span>
            </h1>
        </div>
        <div class="row gutter-xs">
            <a href="{{URL::to('control/category/electro/create')}}" class="btn btn-success">قسم جديد</a>
            </br>
            <table id="demo-dynamic-tables-2" class="table table-middle">
                <thead>
                    <tr>
                    <th>
                        <label class="custom-control custom-control-primary custom-checkbox">
                        <input id="checkAll" class="custom-control-input" type="checkbox">
                        <span class="custom-control-indicator"></span>
                        </label>
                    </th>
                    <th>الشعار</th>
                    <th>لون الشعار</th>
                    <th>اسم القسم</th>
                    <th>اسم القسم بالانجليزية</th>
                    <th>تاريخ الاضافة</th>
                    <th>الحالة</th>
                    <th></th>
                    </tr>
                </thead>
                <tbody>
                   @foreach($cats as $cat)
                        <tr>
                            <td></td>
                            <td>
                            @if($cat->catphoto)
                               <img class="rounded" width="40" height="40" src="{{url('public/assets/img/')}}/{{$cat->catphoto}}" alt=""/>
                            @else
                                <i class="{{$cat->catflag}} fa-2x"></i>
                            @endif
                            </td>
                            <td>{{$cat->catcolor}}</td>
                            <td>{{$cat->catname}}</td>
                            <td>{{$cat->catname_en}}</td>
                            <td>{{ Carbon\Carbon::parse($cat->created_at)->format('d-m-Y ') }}</td>
                            <td>
                            @if($cat->status==0)
                                 <label class="label label-success label-pill">منشور</label>
                            @else
                                 <label class="label label-primary label-pill">تم ايقافه</label>
                            @endif
                            </td>
                            <td>
                                <div class="btn-group pull-right dropdown">
                                <button class="btn btn-link link-muted" aria-haspopup="true" data-toggle="dropdown" type="button">
                                    <span class="icon icon-ellipsis-h icon-lg icon-fw"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="{{route('electro.edit',$cat->id)}}"  class="btn-link" >تعديل القسم</a></li>
                                    <li><a href="{{route('cat.destroy',$cat->id)}}"  class="btn-link" >ايقاف القسم</a></li>
                                </ul>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection